# Generated by Django 4.0.3 on 2022-03-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_galleria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_str', models.CharField(max_length=59)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Galleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='galleria_imgs')),
                ('description', models.TextField()),
                ('timestamp', models.CharField(max_length=101)),
                ('caption', models.CharField(max_length=88)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='el_galleria.category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='el_galleria.location')),
            ],
            options={
                'db_table': 'galleria',
            },
        ),
    ]
